apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poolers.postgresql.cnpg.io
  # annotations удалены для уменьшения размера
spec:
  group: postgresql.cnpg.io
  names:
    plural: poolers
    singular: pooler
    kind: Pooler
    shortNames:
      - plr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # Здесь должна быть схема Pooler — для примера опущена
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
  webhookConversion: null
