---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-postgres-superuser
  namespace: default
spec:
  encryptedData:
    password: AgB3GnvNJzW5EjyP9yVAnKdE8gyD4rDX5Oq08qV4ymbk4NMYVa9PgesnRJvkrIt/tq6ST6NZWolBWS83rbh7At1g5x+C2LYRjrZPsPFIoWiUEOMy6nmdf+HXdx5vs5TGcHdgkzl+nliVzkUtXLWfEYMuPI5/rl56PGFCIaesXwKkAFgq1pkHVK0fpUwysYZx9WoDGDPRxP3OAE5invDnKKxdGavNmMbOO6nFVnobA3dz3fBL8pDIJK8qmDVYa7+3a/Ai+gFYAX6HJBvieuNGV2YaTyoUjcJePmfJtCQbcdfT6PSaJQYEDBjLHJlFvhI5ucPRITYTPCUTZmrrImQDD7+yJK3iSI4oXDDjQDcMKGThPZNUCXSDwWQdyqkNK0xPTfSZh4pB+Sjplf1c/cb3S4l8KA//6gvgRAG3MNZLdwzfGJJ1N179aD0hYRvv90G2XMGX4FBOwFqbR3vBfgG+c1UmSATgvy+od0vDgkgyAStUeHGHkPsbdp5NISyLU6RbWSNqWJrg7cdBn52Jf6je5LmKUnToS0JdKSrTDmbfNM51txtkaevLfjP+VNoH0CMDQF81CjCqSK45p8Xxn5Pk0V2dDG8F5z2kIxJz7x64CzLpeCksXnelItOolxZrod1Ho2dNwmqX1ksfHWHraUkXG3/C9Oo0a5pWJf4EIBe4SZa7gjNKWeW3aoOKi1xoKMmJNIQ4iXHMDePH1EZ8rfw=
    username: AgCAMtD5ll+K/fYZpg14yj7UNFuZhWlEm3hDCi0ge/K2AhjZPD9HG/DwMU9E7TGEI2LTHRbyGE7y9gUt/gkiVPo5alcmU2MhqfaaCPSGudinLOxF0NaeW9cr5+Zp8C/N0d0Boqo0RZxPrM4oJLejm0XSe/2BKDeYI9VO5AljKUF0ne4Z95gh/+TLEwbxlsHCA6H6g1BduvzFs+33WO2x2l2YQjFyIvJKxwllxTSQL5dqWK80bv4RCEpcAIyof0MfZfK52cWRIkJ6w8A+lya0oGMWMxJNx64wPTtg+Rg801H8wtlnH79QxgDgIW5l6npJARxhIUnJP+NuguHoE4DufJYe95bpSTyPZTZv5DL2vGXG20iYSPw+YRPe9pRqhqv0ZdXAPyHsihE+Xx3KQKU/7KyDqHYkykCbRL9f7I9XNX9lmamFFOLPket45OOpFDJUpiIDCcWC48ATWuOZy3I9WFCMkrqF8NZhB/v82LUrH6EqaHWpdlqkUKcN+7hDSseK2UwofRg3VuOzo3et+Sdy2kjlyPcMJcheDoZCjmFLOXFfj2IIei9nv62FaOnwYsLItRHH7DoLChxQuCE7fr4KhqArl7FYk0ttpVOtMfQFbgdc64OBML88ecCqhtfdQu98m96yWKs87gXZVQe+JesWeGxmFoJIUtdk5G1HQgu3Gw1TMdSXJWCLROlkl0MgHQcWgUFcaTJo+yqdtw==
  template:
    metadata:
      creationTimestamp: null
      name: my-postgres-superuser
      namespace: default
