---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCfkTAn8Wnb14Oximd6QF76cY/pjRRc5B8SlrXRUW0Gu+Yt2QEnbTJyLEABtjZjw7rhmMWq971wZAYhC5bmrHcQu2JbvB5a/ya8OPAJF/boRp1RoKmYqD1GztKRTnFvNH64sBfAC+sWwsEN3MSKORDKkkKn8uSt1890CwGfsWmQ+21YMIF4LKuSmPRf7VNdnOwwm41BprwAWr9TKg6TBnse+3a294JvbHr7cKOiUqAkU8aCsBNlDAQAUcKd2Mz9kkRt5W7oHCix2d8+lBrwh/jMdjCW4TRBQVBBMsgB+Xp+QjWRSRpnK1IiVNHm4X8/WP/ymVGGfMeUiWashJQ7v35aBDudsK6PsE/guQ2ark574Q8nkFxOhruz8OvG8TqFq4AvRKrE5B+rBCUwedtVSrR+7GkeH9kKopyuRI9KBJxJNJtwwV4IdZoNUaQSjhu1EeXDdLcczEyehrwvvR8Po/bY8oGg+qYPwDuhSSDyPHG0kVYJPxwiwmlcBOdG+pPhdYJN7EkjS4pQ4CLWHBwPXF5BnVuEMhsbgIhH7fL0jsc339so1193ieqe/RsHuO7FbnZTbXBpBsrKZ6GCzRW0AEmTI+q2u2lp6InJrmiwWEdNWpIaJa/wP3CS1oTJ3H+K4a2cwOQACO3YV45MOkLAWywzGok388tKm+744X9+/1n5Knrv0/MV7lPyiILlBiyyKxLEZAuBexR+VHA+9aw=
    username: AgBfdfwXp+SDhFCuMYapfOL/B6wAvn7icQ7XNjSJuqCoIm0Dz3lt21MoWcTRmKmd8P7aBdkWBW7+vNiv1wcLC14EyVcHu1MNSzgenewiObCN9bKoU6v7ujCy9ZAGnjzW4r4uzWEf2+V+UtjPuB+CiQ1Rh8pCYaNy8l99F5IP87vsGo9n3a+aZjawj2OzrhNjXzN1GhECKghFgUy5lxVA/usGokegZOjdBjYucJHjIE3aOYVDaCqvWZt5ZdQSLg1k9lxNy6O7XQ5wBVpJ39BzTcdcqOFUTpvOq1TGKnP0qOWHjVoMOdVjaXEFcJnuWn6f9iouYtE8/OSLj1UAVjazTeqqrlr8HxZugGlebgs2Bo9wk25DlFDgABdEOqYA/femA/CtNrBU16os4A2XnPQZg2WaqzLWow3NWfa5Q33EsmKZhNUkjXciDjjh8RHigRFbiT9lTjlLWuVVBpFE5KxFh7b56ap4+aKXCh1JoslJJNnIWcQM0MtP4H9IuspcWvnKQ9GGwlkXY0+Q1ISiY74HHf4iO5aLjf90Vowp9qSAsL8+KVVMSO4SzOvq02Lr+S8pq50DykZxxTYOU3FibgEI7Z7bXMjz0CLt3i/CwtDuKpN8crtiMCYidvRKOCeV/9Ad6xp3Wesqv/1lG5Df1LHbYbbAb4qo/xsxdYt+BHFPbEQGXMzQs085j9gQo4xH1kClDSrh54T6cOGAoQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
