---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCR/rVSJh2HQv1FG/J9N4dWUHj0NP/P5+A0OXA6HHM7T3Foij/jS8I4IPFUgOyNycw/r/pafaiF2ebb/LSZSKxnlWdeymrFvJ/K6CTQ0BhZ+4oy4noDaQfxjjcHQA3osbLN87FVb+CaPfF0xcy/fsw/TRkAtRWG914U4jtzbNDIi4Mmktiz6zet0ZLHKJGZuOuwocPaPcEm0nkDlFUj2NGIYE6eIHKFrFNBBj9YXsQGbzyP4Z71AP4E3quZcuqWBjQR74SYenRLNm+2OmpA1S0aj+llCHPa4whbmS267fIAq7CMC2xuSCrT0NkCKFbFh5PF8E5ukttjd/2/B6rL53Qsdl6dLUeMP+7cjr/6zc7i1/nnTNGiKRviH32Sdng313hbKIivRbYV0zJfqaewkCcy5DytBLVHlFD8Db0/QEBBDjqljTntuFWzUbsKugKWjfRdwlgpS+7A+tYv8W+1qF3sos1WUMqlQGLREcCoDwhLPj8uM4Y6hSY8Mi0PWInyLtnup6BVwfNXQXbCsn2tQ8JtMYp7WLx3HXebvTp2MX7RUtLIS8K29Egla6vciMkhUFDmwpgdUTQGNAFsN6RCuBXt3SzMFhFbvndijrBzMor0eouCtxLwAUfte9fcWewHWzrgP6r2p42NHa4DAw4DcJQRLCTrVjczqsDkXiRDYhaCkNIBNFME/QgecU92g4H7nhZvNchZOS5h9LCzMrc=
    username: AgDBZEGfc3Etw0bFpHHFT9T9nEytFL7kf32XC15bFXDpqSC8baPQtClrvIUMeEE/luAJ6vk4/P0eArKoxT23OnTjRo9eAaRAlvBuuWsKcRfplYL7AlQX+7tcWsiudogiXIiV0UN6QNhPIxRGXu4CXnWw3q4P5JI7Ei+ibE1YqNYvyEDGZmol04/WSBCpR5G01JNUeRkC+M6XP0YuBiWhRM3JrsjHjR8dScsdr+RwD7JJdCPgfHVfQd61TZa8kQ40dFp3QPkOZQCLY6dgoS2hoVFqEbC21QPAi2yveR138FSWqNewa7PGDoQnnLEWDuLBScCOuh7bAS5JBIaLBIyY+lw1HFV4tqP6QRazRoDzccuDnNy2in7cTyk5Hnr3lWPdxrTh9DR/NoaSVQdoDtNVhrwo82GuD8ly6kqVUCFmLUNjJCsJC0B9K5OsVFrbZ5pl7Mcjl8tdycrtzwOztmgLqamQuE4RhteeDiAbX1BvwQS13EV44ypTeOCypsnNogwqZTswxAfqumws9JpLB3qIMqVC0U+l3olWe7XPHzCHVCgY8oZ70NE8CPF23VPZEVYDdYQPlYlc+NJDnpFepq6Ewowz2BohrGDotM/yTmlJOafK4Rod78v2FBgYkIoI8WvF5xy8Y6PqZ+gokOCYdmqv91JY9eqA8QwVdFiZ8xq7L9rJvIj90UVDXmq66ITVDWE+AbU/23wXidG/+A==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
