---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-postgres-superuser
  namespace: default
spec:
  encryptedData:
    password: AgBq/Ue2uBTe5XyQTikxSz+uAckFGhBxvZ4reT8NvQh5YrYLNMyoKGtESlhSk0+T7OIPRKQbn9VVU1+IF6oklBhoGf98ZXmsSARdbEXfxTd5BDjMnoVSVc6yoAb/bz89fu7MYymu2PP6Z3HMUh1bMj4kMbuHE9WwrWoBU4FGc5ulLwNGOs86DrFlXGNhBbBwO3MRs3Sh2IYQ+sFDOVNy1Lh+DCr49P4pIMLd3fBtO7s7UM8Wc02hul1bFva3XgN0iUo4MGPuLFiyROmJMFPSiRHBCgKhqe8S/iQGBudegy3EcbO6xW1ltHt6qqkcIWmwG2Yr4PB9QLm/PEh4rwaLCeiNmcUtvXrk6sYvtcwZXcvd/rMtr7b+jkxY9hGOIAbUJerO09dQIgwqETWdopJZWSoYFCG5oMe12QPsuNsYVQN5oGFIDSNfNHtBWupD5PcXRgJ4xFoYqximoRX6XTn/WXB9ev/SGdvcVabwLZ3oeEGOfB5bDFSIYCncY6ou8pIum3tGT4+HCMgA5E4xHN9IJFw++SlTmA/f0G5DEes2cEm1t2dqrDwBhiawidbF4MZyoGp3Td24WScyVqalMyKM4K8Sw0gzFFP4h6ozzB4Yy8Q+iWB80/CVe3FeTS/hKhKPVHsRbN8ve5PfckIq5Vo6yt2b3LIhXlavKMT8Naz0IxH0eea1l6YSrc4dSyIa2aFlzsK27cX20g5mh6CeWz8=
    username: AgBxw6aOmgZ/SjC0cibJSg3leo76FTefnFpkDH8cai7EJKEyHDvnUPizWUd41Rs/kY1h3uPIP2aXYo9oRedYeoO72VbkaaVViQAC53VZQLBz2pUNp0yOdvbmDEPmlnKqi55RTzY8Sn6689mzvWdhuCjKv4buAgpEq7dZC88vzrNl7mdm/kOPNut09L4zOcQo7J46SxY2J/gqzmnF34zbKbgS8BVhjBiYp4Dvm0/KrqTZEu4tLAIgEMWvIyi7IemgrKrNSsKDq6NKJoO+GGO3dCI6zidjJJOPOLTwP3+duUOEvCGvnGR/DwJGtxp9x75LFhRETX6azf0D+oQ8pTeRz4vMHCetr9n7z2t5rxc6BS138vBzpIy/Eyw6e8YkaSbNFMpr/8s/Nd6PP+u0IcyZBNwbvRcCKjqI0olULm3uyd8S+7C0eY04rU8P1x+BMFKleJbVR5yG80WhqMcypk8ouNZIWLUJrh9a+QmQtzvnxFAlE12kx33SnGVLkaXthgtGaYqmxgqMsD8R1uZTB2+rmc2ZT1nyV3LZjZgcCHq2v7ce6LFFDTy2S9rYKzCQzINcSFIGVi6UfEcCirDrEY6srg64QtgqzwlUUnIldOpPYZ1ZbWBB4p88qJ/2eCVgTwVFB6fLduWpk+v81aqkRsW2d4IpNneytgwvq4pOtsqvQB3zuBlMnmg1JGYydFH+mAy374EsVWhxHYzmAA==
  template:
    metadata:
      creationTimestamp: null
      name: my-postgres-superuser
      namespace: default
