---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB5W1hIEwqyvnbt1zhL7Ggo4WzenjsAqwV1ShXqLqZFmpR+0WahoFGM13pb9vn8RTfDvDEuv7JN8mIhTY6Nzfox31P5ceja3XHejRUdJKOKrHoCE5RE12MpKUFHXhJyc8EDtRjNxx+GMAyiTQPsqt0EDP42PXRFcfN6NZTlYqiFcyWBgOGz8Uk/dyJlYDQwGqi8Y1DbRLy99US/lIi3QlJXSyeVR8kByzWq1HxGnBQ4LuBfGp0I70o3UySYOtW1TR9LXVEkpzV40Zl5YSxxFly4XzocEUKJVGFirBEYE+EzAHJLchmFEXg868vmToIKGa6w4E5CcaKd3Jsrd9UI91DU4gJhUG35onVKGaJqWD8phQaRlvs/OcnC4az2kQ9HtJhq9gXxgEY2oCyH+tO5GS2dqeNJG/kk2KlP44Rgtp+EP6CiaqfjGaFWiPd5AdrATDDy1RE6P5fky522VMiNdL6EBaZYgVxYNEyAkKR4QTZ8EFh06hWbtB73MUj3ta8Vo97TNMw+HHmf/BMcfOA4kvtyiH3zz0FmYtLVYIca1Hcxk3hX9Gvr61Bnel5bWgJISqkenfYjxt2oi72bXaOxBoKvzF6/T4zo0KDyZjnLexO41nSTvH8eJCBP44jxsAVUpyRFJ73ku3/85xBM/x2soAsUKCBBrn6204zztz3wjygkKu175/TXlanQct8uWx8eYFiFCFfqr8ME13k8iYA=
    username: AgAQcPXjlmaTkKaNkWxSOf1P5GZcF8GPcbjEnhJBIBUYqUslvTp5Pk6MPkxWmi84jiEHtisu6wKmt+xn9Y95WOcrBa2HBXo3xVwfQ9bcXWTuiIkSnoDrfYdopnIyoweq0CMrWYORV0hv2ARzaDhdDFfGesgExV2Xz+8xh8Jfzx5eNfHPfpYU84pGxRr4F1NsYwQqZm/gRbFntgG2uY84nDddNbpJxAyu8vhZS0Pegs2AD5YELw6Ey3ahF/Kp++rB10Q4wkoulTZfKsUHfHyqsRq33N+0z7tli0rv3h9hZygU6dGre7jcBJjx7PAeGBPLQP6CZjz+7t9FncOHv9Ih2VwC2BjHU3TZ6ZPqoJW5/7q75yFsxsGqCir1020rFkEOGsa4nQmnv+gQvPrX3bUrXCiuVwhmqDeMFJKF8FE/AGb2HkAPo8tiXBxvFm5FYv70m8fS7jUkoPd/4Pp0FyOJu2Qx/oKWE21Q2SdU+nzsLENHw1fYDD4ncSVlPG/gHCP3CgshcFXvH/fIkeIbBsGOI0uRLhrktqSBty2riQapSbcmNl4ExzCjm85X6paKMWCkVfahbnV/fT5dKKGDvtg8fCmL/PrtnarSZzH+fE5gF9oP8wOsOQnCMqQm4lUVOKRY3eRgC4Rd+vLYc80u21PFOtEPYOtGsAJA2HcVusXiaBDDEep6mASFjjVKNd6Rnh6SdUHUa35XfkxEag==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
