---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB4kUCqTMhdYqx66f42BOnbMed0kqvArSmHDivs7t260tJQYUJlgUlSdx8rgn9chAtjAwCGDL7MLj1fy1MGM/q75QTl0xzajRR2JQSUxI+0quxZA4uWJ0ZwnxZf1KLX9Euu6UKCJk3i1MMZq9rCR8hDHaPRlyz2z1i3t9MASqVoRgaF8rCh+MdtT1+v6vltsPeHwbdMFfRgoIb4oeA2J3iIZ2eS0RehHaNryz3aiX8vPQpWWe9bFYA1dcvBD58v3C/+ahlZmtdrSllxgKyC97zcTjYsD4PX9u3ZyD+mlS3ZTgFF0lhBKnN6lwQE/ikwmD7V1OPbQRmle+WCV0+BDvoq64wBQ7qChQ4pTRKNmYwGqv2LmgYQs8bfEkL5DJrtNHL5LYzAsFFYGP7ZmAfvaRVuO0EPFOxzmHGeq3vbjCEWftZdBzF8JPgxSLJuQBL7KhSm1bAk9YGvJ4KHIs/D6xoZY7SzSw+2QLm/fO5ax7pEUvDY/M+qwxtuLDSoCAVLQ7bTihue8OAxLlDQXsO4qbK9kGdiLn4EwSPjBqBBxUguP7NRSmHts+TgNGNB9YVNGSJ8UImsQNe7BKf/JKIF0BYTFlIR4sBGFzik88R4YSC4N7yiNl2juRjtqKEp+fCFpmbHJ3HEuEFKlmE8Hma2N65haZPNrhgU1OmDw3Jza3jS4v8gofdQCAno67+Jnqj6vwFvKFNChlxLdramCFo=
    username: AgBBMDK01jYxP5HiYWeIO4rTjQwkVYiVxQ/XKTG+b2HoxEWxUVGs4cfQRLIMPEF898YRCdIaMLafgEogokcysnGZ+FU+cGp1TlSM/Hqa9LUH2YlqZ295Mm9lce0XVnSqwPV2hBQeXiLBIeQGZ8GS57RjtUGNuthQAnpURrtvoIF7aboJfAc75n8xHxtcikpO8GcfHShFgt2+jSUeN62YlMIlofjiMqY/Sr54LMo4UM2HBe78ySTkbZXzI9/NLOvY4Cyp51i2Kq94FJqX0DR/+1ggE0GPUAKIdFJYBRMDYe1qSJQOZwHtJU0MNNuDHSscvb1JJI5hVn5y0aAWY3aiqX/RQ6g+aEGtGvBHTUuA1d4EsHuZsjsBR/kk6enRyqd0jwPpkhX2ep+ZIkO7/c9EHHJmrJtmb1EitiJKh4pI2p0klokNPN5L6TSQ5Vr64YrVG/KwJ6rKtZxfnEn1UGWPL6gxGCU3RfPV5g5C52zPKYl0AB8j2ilBmXhwmujKDfqayxZeQK9RK0vApgqhEY7cUpiSwrui5ImicZLyaWUSf+x+FXWg8ZEervnFdjpGqxbmhUVkahOp2UnhIA/h8ARQNtZqRhYWy+ey8XRpnsab/DSFnd0PdH59RhaRsc8RxlxkSC1a2bNRI9HWe6qOOfBMPGB1T4vQxWCvm6dfVL1xxIZx54NKHi41k3RPLWYl7KpjFu/PAyA17RGWhA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
